import random
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from django.utils import timezone
from polls.models import Question, Choice

class Command(BaseCommand):
    help = 'Seeds the database with thousands of questions and choices'

    def handle(self, *args, **kwargs):
        self.stdout.write("Wiping old data...")
        Choice.objects.all().delete()
        Question.objects.all().delete()
        User.objects.filter(is_superuser=False).delete()

        self.stdout.write("Creating 50 Authors...")
        users = [
            User(username=f"author_{i}", email=f"author{i}@example.com")
            for i in range(50)
        ]
        User.objects.bulk_create(users)
        users_list = list(User.objects.filter(is_superuser=False))

        self.stdout.write("Creating 5,000 Questions...")
        questions = [
            Question(
                question_text=f"Autogenerated Scale Question #{i}?",
                pub_date=timezone.now() - timezone.timedelta(days=random.randint(0, 365)),
                author=random.choice(users_list)
            )
            for i in range(5000)
        ]
        Question.objects.bulk_create(questions, batch_size=500)
        
        questions_list = list(Question.objects.all())

        self.stdout.write("Creating 15,000 Choices...")
        choices = []
        for q in questions_list:
            for j in range(3):
                choices.append(
                    Choice(
                        question=q,
                        choice_text=f"Option {j} for Q{q.id}",
                        votes=random.randint(0, 100)
                    )
                )
        
        Choice.objects.bulk_create(choices, batch_size=500)

        self.stdout.write(self.style.SUCCESS("Database successfully seeded!"))
        